projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: jwsyipvccnexhe35bygp5m4jpy
        frontend: javascript
        framework: angular
        maxDepth: 2
extensions:
  amplify:
    version: 3
